### ISSUE TITLE
Error running example on README page 

### ISSUE THREAD

**Issue by raprasad** [opendp/smartnoise-sdk#361]
(Using pyenv and Python 3.8.7)

**Code**: "[script](https://github.com/opendp/smartnoise-sdk#script)" example on the README.md page

**Error**: sqlite error when running this line:
  - `df = execute_private_query(reader, schema, 0.3, 'SELECT AVG("petal width (cm)") AS petal FROM dbo.iris')`

**Exception**: 
```
df = execute_private_query(reader, schema, 0.3, 'SELECT AVG("petal width (cm)") AS petal FROM dbo.iris')
Traceback (most recent call last):
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "(": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/pandasql/sqldf.py", line 61, in __call__
    result = read_sql(query, conn)
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/pandas/io/sql.py", line 521, in read_sql
    return pandas_sql.read_query(
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/pandas/io/sql.py", line 1308, in read_query
    result = self.execute(*args)
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/pandas/io/sql.py", line 1176, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in execute
    return self._exec_driver_sql(
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1546, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT COUNT ( DISTINCT primary_key ) AS keycount, SUM ( petal_width__0_cm_1_ ) AS sum_petal_width__0_cm_1_, COUNT ( petal_width__0_cm_1_ ) AS count_petal_width__0_cm_1_ FROM ( SELECT *, ROW_NUMBER ( ) OVER ( PARTITION BY primary_key ORDER BY RANDOM ( ) ) AS row_num FROM ( SELECT primary_key AS primary_key, CASE WHEN petal_width__0_cm_1_ < 0 THEN 0 WHEN petal_width__0_cm_1_ > 3 THEN 3 ELSE  petal_width__0_cm_1_ END AS petal_width__0_cm_1_ FROM df_for_diffpriv1234 ) AS clamped ) AS per_key_random WHERE per_key_random.row_num <= 1]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/opendp/smartnoise/sql/__init__.py", line 39, in execute_private_query
    rowset = PrivateReader(reader, schema, budget).execute(query)
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/opendp/smartnoise/sql/private_reader.py", line 177, in execute
    return self._execute_ast(query)
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/opendp/smartnoise/sql/private_reader.py", line 258, in _execute_ast
    db_rs = self._get_reader(subquery)._execute_ast(subquery)
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/opendp/smartnoise/sql/reader/base.py", line 19, in _execute_ast
    return self.execute(query_string)
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/opendp/smartnoise/sql/reader/pandas.py", line 142, in execute
    q_result = sqldf(clean_query(query), locals())
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/pandasql/sqldf.py", line 156, in sqldf
    return PandaSQL(db_uri)(query, env)
  File "/Users/ramanprasad/.pyenv/versions/sdk-test/lib/python3.8/site-packages/pandasql/sqldf.py", line 63, in __call__
    raise PandaSQLException(ex)
pandasql.sqldf.PandaSQLException: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT COUNT ( DISTINCT primary_key ) AS keycount, SUM ( petal_width__0_cm_1_ ) AS sum_petal_width__0_cm_1_, COUNT ( petal_width__0_cm_1_ ) AS count_petal_width__0_cm_1_ FROM ( SELECT *, ROW_NUMBER ( ) OVER ( PARTITION BY primary_key ORDER BY RANDOM ( ) ) AS row_num FROM ( SELECT primary_key AS primary_key, CASE WHEN petal_width__0_cm_1_ < 0 THEN 0 WHEN petal_width__0_cm_1_ > 3 THEN 3 ELSE  petal_width__0_cm_1_ END AS petal_width__0_cm_1_ FROM df_for_diffpriv1234 ) AS clamped ) AS per_key_random WHERE per_key_random.row_num <= 1]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

**Comment by joshua-oss** [comment]
Fixed
