### ISSUE TITLE
Error during preprocessing for a GAN-based synthesizer

### ISSUE THREAD

**Issue by neat-web** [opendp/smartnoise-sdk#509]
### Subject of the issue
A `TypeError` is raised when preprocessing for a GAN-based synthesizer with a categorical column that contains just one value.

### Environment
* Windows 10, Python 3.8
* `smartnoise-synth` installed via pip (version 0.3.2)

### Steps to reproduce
I installed the latest `smartnoise-synth` version and tried to train a GAN-based synthesizer e.g. `PATECTGAN`. The data contains a categorical column with just one value. I used an inferred `TableTransformer` with the default one-hot style for preprocessing.

### Expected behaviour
Preprocessing works and the synthesizer can be trained.

### Actual behaviour
A `TypeError` is raised during preprocessing. The traceback is shown below:
```python
Traceback (most recent call last):
  ...
  File "...\venv\lib\site-packages\snsynth\pytorch\nn\patectgan.py", line 551, in fit
    self.train(data, transformer=transformer, categorical_columns=categorical_columns, ordinal_columns=ordinal_columns, continuous_columns=continuous_columns, preprocessor_eps=preprocessor_eps, nullable=nullable)
  File "...\venv\lib\site-packages\snsynth\pytorch\nn\patectgan.py", line 214, in train
    train_data = np.array([
  File "...\venv\lib\site-packages\snsynth\pytorch\nn\patectgan.py", line 215, in <listcomp>
    [float(x) if x is not None else 0.0 for x in row] for row in train_data
  File "...\venv\lib\site-packages\snsynth\pytorch\nn\patectgan.py", line 215, in <listcomp>
    [float(x) if x is not None else 0.0 for x in row] for row in train_data
TypeError: float() argument must be a string or a number, not 'tuple'
```

### Possible solution
The current implementation of the `OneHotEncoder` outputs a tuple, even if its `output_width` is one. Thus, the `TableTransformer` appends the tuple to the `out_row` list. This results in a `TypeError` later on during creation of the training data array.

**Comment by neat-web** [comment]
The issue is fixed in version 0.3.3.

The discussion in the related PR concludes that there is a slight incompatibility with transformers from the `sklearn` library that is not relevant currently. Also, the sporadically failing CI tests might lead to a deprecation of poorly performing GAN based synthesizers in the future.
