### ISSUE TITLE
Failed to import snsql

### ISSUE THREAD

**Issue by WCY-dt** [opendp/smartnoise-sdk#608]
I followed the instruction to use pip to install the package. But I failed to import the package:

```python
>>> import snsql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python312\Lib\site-packages\snsql\__init__.py", line 1, in <module>
    from .connect import from_connection, from_df
  File "E:\Python312\Lib\site-packages\snsql\connect.py", line 1, in <module>
    from .sql.private_reader import PrivateReader
  File "E:\Python312\Lib\site-packages\snsql\sql\__init__.py", line 1, in <module>
    from .private_reader import PrivateReader
  File "E:\Python312\Lib\site-packages\snsql\sql\private_reader.py", line 6, in <module>
    from snsql.sql.odometer import OdometerHeterogeneous
  File "E:\Python312\Lib\site-packages\snsql\sql\odometer.py", line 2, in <module>
    from snsql.sql.privacy import Privacy
  File "E:\Python312\Lib\site-packages\snsql\sql\privacy.py", line 2, in <module>
    from ._mechanisms import *
  File "E:\Python312\Lib\site-packages\snsql\sql\_mechanisms\__init__.py", line 1, in <module>
    from .laplace import Laplace
  File "E:\Python312\Lib\site-packages\snsql\sql\_mechanisms\laplace.py", line 3, in <module>
    from opendp.transformations import make_sum, make_clamp
  File "E:\Python312\Lib\site-packages\opendp\__init__.py", line 1, in <module>
    from opendp.mod import Transformation, Measurement, OpenDPException, UnknownTypeException
  File "E:\Python312\Lib\site-packages\opendp\mod.py", line 13, in <module>
    from opendp._lib import AnyMeasurement, AnyTransformation, AnyDomain, AnyMetric, AnyMeasure, AnyFunction
  File "E:\Python312\Lib\site-packages\opendp\_lib.py", line 46, in <module>
    lib, lib_path = _load_library()
                    ^^^^^^^^^^^^^^^
  File "E:\Python312\Lib\site-packages\opendp\_lib.py", line 31, in _load_library
    raise Exception(f"Expected exactly one binary to be present. Got: {lib_dir_file_names}")
Exception: Expected exactly one binary to be present. Got: []
```

I have tried in both Python3.12 and Python3.9, but none of them succeed.

**Comment by WCY-dt** [comment]
After I updated OpenDP to v0.11.1, the problem is solved.

**Comment by joshua-oss** [comment]
Thanks for reporting this! I believe this was a windows issue related to #604 and should be fixed in #613, deployed to PyPi. If you pip install to the 1.0.5 or higher version

**Comment by WCY-dt** [comment]
Great! Thanks a lot for fixing this!
